version: '3.8'

services:
  metabase:
    image: metabase/metabase:latest
    ports: ["3000:3000"]
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 5432
      MB_DB_USER: metabase
      MB_DB_PASS: secret
      MB_DB_HOST: postgres
    depends_on: [postgres]
    networks: [metanet]

  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: metabase
      POSTGRES_USER: metabase
      POSTGRES_PASSWORD: secret
    volumes: [postgres-data:/var/lib/postgresql/data]
    networks: [metanet]

  mongo:
    image: mongo:latest
    ports: ["27017:27017"]
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    volumes:
      - mongo-data:/data/db
      - ./data:/data
    networks: [metanet]

  python-loader:
    build:
      context: .
      dockerfile: Dockerfile-python
    volumes:
      - ./data:/data
      - ./scripts:/app/scripts
    depends_on: [mongo]
    networks: [metanet]

networks:
  metanet:

volumes:
  postgres-data:
  mongo-data: